### ISSUE TITLE
Sign in process doesn't allow for user input

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/tweet-old-post#955] opened 2024-05-08 10:00 UTC
### Description

A user reported that he can no longer choose the Facebook profile that should be linked to his WP instance.

### Step-by-step reproduction instructions

1. Go to ROP
2. Try to connect to Facebook

The connection will be made, but you cannot input the profile or choose which pages to appear, as it was before.

### Screenshots, screen recording, code snippet or Help Scout ticket

Once you click on sign in, this will appear:
<img width="1348" alt="image" src="https://github.com/Codeinwp/tweet-old-post/assets/86592992/8fb8798e-3450-4a74-b16f-81feacf3a84d">

ref:https://secure.helpscout.net/conversation/2590687579/418114?viewId=212385

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by AndreeaCristinaRadacina** [comment] 2024-05-15 06:13
+1 https://secure.helpscout.net/conversation/2597543360/418836?viewId=212385

**Comment by Soare-Robert-Daniel** [comment] 2024-05-20 12:31
This was caused by the re-authorization process, which tries to log in to the previously saved users. One quick way for the user to choose the profile is to use incognito mode so that Facebook does not reuse the cookies.

**Comment by AndreeaCristinaRadacina** [comment] 2024-05-20 14:31
@Soare-Robert-Daniel I shared this solution, but the answer is not positive regarding the result.

**Comment by Soare-Robert-Daniel** [comment] 2024-05-29 07:53
Besides this, we should also update the Facebook API version since Facebook is starting to move on: https://github.com/Codeinwp/tweet-old-post/blob/6c8d5852276b4ca3ab7090681d4f8c5397189de8/includes/admin/services/class-rop-facebook-service.php#L166

https://developers.facebook.com/docs/graph-api/changelog

**Comment by Soare-Robert-Daniel** [comment] 2024-05-29 14:49
@AndreeaCristinaRadacina, I have reverted to the old behavior for authentication. You can keep an eye on if the users still have this difficulty.

**Comment by AndreeaCristinaRadacina** [comment] 2024-05-30 07:38
As discussed, the login is possible, but the whole modal with permissions and page selection is gone.

**Comment by Soare-Robert-Daniel** [comment] 2024-05-30 09:12
@AndreeaCristinaRadacina, we can not do too much on our part. Once permission has been granted, Facebook will not ask again (also mentioned in their docs).

Based on this, a possible solution for the users to re-add the asking stage is to remove the post permission in their Facebook dashboard, as shown in the video below. 

If they have multiple websites, this approach might be problematic since if they do this for one website, the login on other websites might be revoked since the access key will be invalid. 

![Image](https://github.com/Codeinwp/tweet-old-post/assets/17597852/68e8515e-684a-44d0-a713-839f006c1d54)

https://github.com/Codeinwp/tweet-old-post/assets/17597852/d6b508ea-ccb9-4259-b009-36c444b4e9aa

**Comment by Soare-Robert-Daniel** [comment] 2024-06-07 07:58
@AndreeaCristinaRadacina, I tweaked the login process again, and the account selection is now showing on my end 🙏

**Closed** 2024-06-25 09:25 UTC
Labels: bug, medium, customer report, Priority-Medium
