### ISSUE TITLE
Thoughts on advanced scheduling

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/tweet-old-post#49] opened 2016-04-13 15:55 UTC
@selu91 we would need to find a way on how we can have pricing plans for ROP and offer advanced scheduling + custom schedule only to business+ users.

Josh suggested to do this based on a license check, we should also grandfather all existing users.

**Comment by selu91** [comment] 2016-04-21 10:27
@contactashish13 we need to show in the tabs just the active networks. For instance here: 

http://prntscr.com/auyl3j 

I have only twitter available and is showing all the networks. Also if we have just one network you need to not show all tabs and just the tab for that network.

**Comment by ineagu** [comment] 2016-04-21 10:33
layout can also be improved a little bit, here is a na example that I like
: https://player.vimeo.com/video/151662368 ( how date/time is displayed )

On Thu, Apr 21, 2016 at 12:27 PM, Marius Cristea <notifications@github.com>
wrote:

> @contactashish13 <https://github.com/contactashish13> we need to show in
> the tabs just the active networks. For instance here:
>
> http://prntscr.com/auyl3j
>
> I have only twitter available and is showing all the networks. Also if we
> have just one network you need to not show all tabs and just the tab for
> that network.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/tweet-old-post/issues/49#issuecomment-212847034>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by selu91** [comment] 2016-04-21 10:34
@ineagu yes, i will talk with andrei or claudiu for design

**Comment by selu91** [comment] 2016-04-21 10:36
@contactashish13 let's hide the sidebar with networks if is just one network active.

**Comment by ineagu** [comment] 2016-04-21 10:36
ok, probably claudiu can do some basic one, not very different than wp
default design and what we have

On Thu, Apr 21, 2016 at 12:34 PM, Marius Cristea <notifications@github.com>
wrote:

> @ineagu <https://github.com/ineagu> yes, i will talk with andrei or
> claudiu for design
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/tweet-old-post/issues/49#issuecomment-212848546>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by ineagu** [comment] 2016-04-21 10:36
edit/delet probably can be just some small icons to gain some space

On Thu, Apr 21, 2016 at 12:35 PM, Ionut Neagu <hi@ionutn.com> wrote:

> ok, probably claudiu can do some basic one, not very different than wp
> default design and what we have
>
> On Thu, Apr 21, 2016 at 12:34 PM, Marius Cristea <notifications@github.com
> > wrote:
>
>> @ineagu <https://github.com/ineagu> yes, i will talk with andrei or
>> claudiu for design
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Codeinwp/tweet-old-post/issues/49#issuecomment-212848546>
>>
>
>
>
> --
> Ionut Neagu
> http://themeisle.com | http://codeinwp.com | http://ionutn.com
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by selu91** [comment] 2016-04-21 10:39
ok, i will send him your suggestions.

**Comment by selu91** [comment] 2016-04-21 11:36
Ok, here are all the issues:
 
- we need to show in the tabs just the active networks. For instance here: http://prntscr.com/auyl3j I have only twitter available and is showing all the networks. Also if we have just one network, you hide the sidebar with networks. 


- Why aren't you using the getNetworks method here:   
https://github.com/Codeinwp/tweet-old-post/blob/development/inc/view-advancedscheduling.php#L60-L62

- I see the times are not working properly: 
http://prntscr.com/auyunf 

- I would like to have all the css classes and ids prefixed by `rop `slug. 

- I would like to move the whole logic from here: https://github.com/Codeinwp/tweet-old-post/blob/development/inc/view-advancedscheduling.php#L96-L104 
In a separate method, having as arguments the network and base time and in return to get the future timestamp. 

- If the plugin is not started to post, we dont show anything on the timeline of the advanced schedule, just a message smth like: "you need to start the plugin in order to view the future shares"

- Why are you not using here: https://github.com/Codeinwp/tweet-old-post/blob/development/inc/view-advancedscheduling.php#L100 the same getNextTweetTime method having as base time the getTime() method ? 

-  here https://github.com/Codeinwp/tweet-old-post/blob/development/inc/view-advancedscheduling.php#L138  you dont need to convert to gmt, all the dates are relative to the getTime(), which is the server time.

**Comment by selu91** [comment] 2016-04-22 12:41
the update_actions is not working, you forgot to add it in the ajax switch. Please double check all the actions to be in place, there is a big plugin and will have a huge impact if we have any problem

**Comment by selu91** [comment] 2016-04-22 12:58
also, you have increased the log checking time. Please change it back.

**Comment by selu91** [comment] 2016-04-22 13:03
on reset action please clear also the buffer for each network.

**Comment by contactashish13** [comment] 2016-04-22 17:44
I'm not sure what you mean by "you have increased the log checking time. Please change it back."

on reset action please clear also the buffer for each network. - this functionality already exists.

**Comment by selu91** [comment] 2016-04-22 18:02
For 1st: https://github.com/Codeinwp/tweet-old-post/blob/development/js/master.js#L491 

For 2nd i thought that is not there. Perfect !

**Comment by contactashish13** [comment] 2016-04-23 05:11
I've checked in these features.

For grouping by date, I've added a (bad looking!) div with a red border.

The time of the first post as displayed on the schedule is 3s off from what the countdown timer shows. I've checked and it seems the countdown timer runs 3s too early. If you agree, I can see where to fix it.

**Comment by selu91** [comment] 2016-04-23 05:20
Yes, thats ok, you can check
Pe 23 apr. 2016 8:11 a.m., "contactashish13" <notifications@github.com> a
scris:

**Comment by contactashish13** [comment] 2016-04-23 07:13
I tried to fix the issue but can't seem to find the root cause. Can you test it at your end and see if you also get a 3s delay or is it dependent on the WP instance?

**Comment by selu91** [comment] 2016-04-23 21:42
i think it's dependendent. What i would like to have, when starting the plugin, the first tweet from the advanced schedule to be according to the coundown.

**Comment by contactashish13** [comment] 2016-04-24 08:07
The first tweet is shown according the to countdown - the data-timestamp attribute of the span is identical to the timestamp used to calculate the time shown in the schedule but the countdown ends 3s before it is supposed to (or starts 3s before it is supposed to)

**Comment by selu91** [comment] 2016-04-24 08:24
That s ok. Thank you!
Pe 24 apr. 2016 11:07 a.m., "contactashish13" <notifications@github.com> a
scris:

**Comment by selu91** [comment] 2016-04-25 09:49
all seems ok now. Thank you !

**Closed by selu91** 2016-04-25 09:49 UTC
